<?php
/**
 * PurchaseCreditNote
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Sage One - Accounts - v3 UKI
 *
 * Documentation of the Sage Business Cloud Accounting API.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.43
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * PurchaseCreditNote Class Doc Comment
 *
 * @category Class
 * @description ### Endpoint Availability  * Accounting Plus: 🇨🇦, 🇫🇷, 🇮🇪, 🇬🇧, 🇺🇸  ### Access Control Restrictions  Requires the authenticated user to have any of the following roles in the area &#x60;Purchases&#x60;: Full Access, Restricted Access
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class PurchaseCreditNote implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'PurchaseCreditNote';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'legacy_id' => 'int',
        'id' => 'string',
        'displayed_as' => 'string',
        'path' => 'string',
        'created_at' => '\DateTime',
        'updated_at' => '\DateTime',
        'links' => '\Swagger\Client\Model\Link[]',
        'editable' => 'bool',
        'vat_reverse_charge' => 'bool',
        'transaction' => '\Swagger\Client\Model\Transaction',
        'transaction_type' => '\Swagger\Client\Model\Base',
        'postponed_accounting' => 'bool',
        'import' => 'bool',
        'vat_exempt_consignment' => 'bool',
        'deleted_at' => '\DateTime',
        'is_cis' => 'bool',
        'cis_applicable_amount' => 'double',
        'base_currency_cis_applicable_amount' => 'double',
        'total_after_cis_deduction' => 'double',
        'base_currency_total_after_cis_deduction' => 'double',
        'has_cis_labour' => 'bool',
        'has_cis_materials' => 'bool',
        'contact' => '\Swagger\Client\Model\Contact',
        'base_currency_total_itc_amount' => 'double',
        'total_itc_amount' => 'double',
        'base_currency_total_itr_amount' => 'double',
        'total_itr_amount' => 'double',
        'part_recoverable' => 'bool',
        'contact_name' => 'string',
        'contact_reference' => 'string',
        'date' => '\DateTime',
        'original_invoice_date' => '\DateTime',
        'reference' => 'string',
        'vendor_reference' => 'string',
        'notes' => 'string',
        'total_quantity' => 'double',
        'net_amount' => 'double',
        'tax_amount' => 'double',
        'total_amount' => 'double',
        'payments_allocations_total_amount' => 'double',
        'payments_allocations_total_discount' => 'double',
        'total_paid' => 'double',
        'outstanding_amount' => 'double',
        'currency' => '\Swagger\Client\Model\Base',
        'exchange_rate' => 'double',
        'inverse_exchange_rate' => 'string',
        'base_currency_net_amount' => 'double',
        'base_currency_tax_amount' => 'double',
        'base_currency_total_amount' => 'double',
        'base_currency_outstanding_amount' => 'double',
        'status' => '\Swagger\Client\Model\Base',
        'void_reason' => 'string',
        'credit_note_lines' => '\Swagger\Client\Model\PurchaseCreditNoteLineItem[]',
        'tax_analysis' => '\Swagger\Client\Model\ArtefactTaxAnalysis[]',
        'detailed_tax_analysis' => '\Swagger\Client\Model\ArtefactDetailedTaxAnalysis',
        'payments_allocations' => '\Swagger\Client\Model\PaymentAllocation[]',
        'last_paid' => '\DateTime',
        'tax_address_region' => '\Swagger\Client\Model\Base',
        'tax_reconciled' => 'bool',
        'migrated' => 'bool',
        'tax_calculation_method' => 'string',
        'withholding_tax_rate' => 'double',
        'withholding_tax_amount' => 'double',
        'base_currency_withholding_tax_amount' => 'double'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'legacy_id' => 'int32',
        'id' => null,
        'displayed_as' => null,
        'path' => null,
        'created_at' => 'date-time',
        'updated_at' => 'date-time',
        'links' => null,
        'editable' => null,
        'vat_reverse_charge' => null,
        'transaction' => null,
        'transaction_type' => null,
        'postponed_accounting' => null,
        'import' => null,
        'vat_exempt_consignment' => null,
        'deleted_at' => 'date-time',
        'is_cis' => null,
        'cis_applicable_amount' => 'double',
        'base_currency_cis_applicable_amount' => 'double',
        'total_after_cis_deduction' => 'double',
        'base_currency_total_after_cis_deduction' => 'double',
        'has_cis_labour' => null,
        'has_cis_materials' => null,
        'contact' => null,
        'base_currency_total_itc_amount' => 'double',
        'total_itc_amount' => 'double',
        'base_currency_total_itr_amount' => 'double',
        'total_itr_amount' => 'double',
        'part_recoverable' => null,
        'contact_name' => null,
        'contact_reference' => null,
        'date' => 'date',
        'original_invoice_date' => 'date',
        'reference' => null,
        'vendor_reference' => null,
        'notes' => null,
        'total_quantity' => 'double',
        'net_amount' => 'double',
        'tax_amount' => 'double',
        'total_amount' => 'double',
        'payments_allocations_total_amount' => 'double',
        'payments_allocations_total_discount' => 'double',
        'total_paid' => 'double',
        'outstanding_amount' => 'double',
        'currency' => null,
        'exchange_rate' => 'double',
        'inverse_exchange_rate' => null,
        'base_currency_net_amount' => 'double',
        'base_currency_tax_amount' => 'double',
        'base_currency_total_amount' => 'double',
        'base_currency_outstanding_amount' => 'double',
        'status' => null,
        'void_reason' => null,
        'credit_note_lines' => null,
        'tax_analysis' => null,
        'detailed_tax_analysis' => null,
        'payments_allocations' => null,
        'last_paid' => 'date',
        'tax_address_region' => null,
        'tax_reconciled' => null,
        'migrated' => null,
        'tax_calculation_method' => null,
        'withholding_tax_rate' => 'double',
        'withholding_tax_amount' => 'double',
        'base_currency_withholding_tax_amount' => 'double'
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'legacy_id' => 'legacy_id',
        'id' => 'id',
        'displayed_as' => 'displayed_as',
        'path' => '$path',
        'created_at' => 'created_at',
        'updated_at' => 'updated_at',
        'links' => 'links',
        'editable' => 'editable',
        'vat_reverse_charge' => 'vat_reverse_charge',
        'transaction' => 'transaction',
        'transaction_type' => 'transaction_type',
        'postponed_accounting' => 'postponed_accounting',
        'import' => 'import',
        'vat_exempt_consignment' => 'vat_exempt_consignment',
        'deleted_at' => 'deleted_at',
        'is_cis' => 'is_cis',
        'cis_applicable_amount' => 'cis_applicable_amount',
        'base_currency_cis_applicable_amount' => 'base_currency_cis_applicable_amount',
        'total_after_cis_deduction' => 'total_after_cis_deduction',
        'base_currency_total_after_cis_deduction' => 'base_currency_total_after_cis_deduction',
        'has_cis_labour' => 'has_cis_labour',
        'has_cis_materials' => 'has_cis_materials',
        'contact' => 'contact',
        'base_currency_total_itc_amount' => 'base_currency_total_itc_amount',
        'total_itc_amount' => 'total_itc_amount',
        'base_currency_total_itr_amount' => 'base_currency_total_itr_amount',
        'total_itr_amount' => 'total_itr_amount',
        'part_recoverable' => 'part_recoverable',
        'contact_name' => 'contact_name',
        'contact_reference' => 'contact_reference',
        'date' => 'date',
        'original_invoice_date' => 'original_invoice_date',
        'reference' => 'reference',
        'vendor_reference' => 'vendor_reference',
        'notes' => 'notes',
        'total_quantity' => 'total_quantity',
        'net_amount' => 'net_amount',
        'tax_amount' => 'tax_amount',
        'total_amount' => 'total_amount',
        'payments_allocations_total_amount' => 'payments_allocations_total_amount',
        'payments_allocations_total_discount' => 'payments_allocations_total_discount',
        'total_paid' => 'total_paid',
        'outstanding_amount' => 'outstanding_amount',
        'currency' => 'currency',
        'exchange_rate' => 'exchange_rate',
        'inverse_exchange_rate' => 'inverse_exchange_rate',
        'base_currency_net_amount' => 'base_currency_net_amount',
        'base_currency_tax_amount' => 'base_currency_tax_amount',
        'base_currency_total_amount' => 'base_currency_total_amount',
        'base_currency_outstanding_amount' => 'base_currency_outstanding_amount',
        'status' => 'status',
        'void_reason' => 'void_reason',
        'credit_note_lines' => 'credit_note_lines',
        'tax_analysis' => 'tax_analysis',
        'detailed_tax_analysis' => 'detailed_tax_analysis',
        'payments_allocations' => 'payments_allocations',
        'last_paid' => 'last_paid',
        'tax_address_region' => 'tax_address_region',
        'tax_reconciled' => 'tax_reconciled',
        'migrated' => 'migrated',
        'tax_calculation_method' => 'tax_calculation_method',
        'withholding_tax_rate' => 'withholding_tax_rate',
        'withholding_tax_amount' => 'withholding_tax_amount',
        'base_currency_withholding_tax_amount' => 'base_currency_withholding_tax_amount'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'legacy_id' => 'setLegacyId',
        'id' => 'setId',
        'displayed_as' => 'setDisplayedAs',
        'path' => 'setPath',
        'created_at' => 'setCreatedAt',
        'updated_at' => 'setUpdatedAt',
        'links' => 'setLinks',
        'editable' => 'setEditable',
        'vat_reverse_charge' => 'setVatReverseCharge',
        'transaction' => 'setTransaction',
        'transaction_type' => 'setTransactionType',
        'postponed_accounting' => 'setPostponedAccounting',
        'import' => 'setImport',
        'vat_exempt_consignment' => 'setVatExemptConsignment',
        'deleted_at' => 'setDeletedAt',
        'is_cis' => 'setIsCis',
        'cis_applicable_amount' => 'setCisApplicableAmount',
        'base_currency_cis_applicable_amount' => 'setBaseCurrencyCisApplicableAmount',
        'total_after_cis_deduction' => 'setTotalAfterCisDeduction',
        'base_currency_total_after_cis_deduction' => 'setBaseCurrencyTotalAfterCisDeduction',
        'has_cis_labour' => 'setHasCisLabour',
        'has_cis_materials' => 'setHasCisMaterials',
        'contact' => 'setContact',
        'base_currency_total_itc_amount' => 'setBaseCurrencyTotalItcAmount',
        'total_itc_amount' => 'setTotalItcAmount',
        'base_currency_total_itr_amount' => 'setBaseCurrencyTotalItrAmount',
        'total_itr_amount' => 'setTotalItrAmount',
        'part_recoverable' => 'setPartRecoverable',
        'contact_name' => 'setContactName',
        'contact_reference' => 'setContactReference',
        'date' => 'setDate',
        'original_invoice_date' => 'setOriginalInvoiceDate',
        'reference' => 'setReference',
        'vendor_reference' => 'setVendorReference',
        'notes' => 'setNotes',
        'total_quantity' => 'setTotalQuantity',
        'net_amount' => 'setNetAmount',
        'tax_amount' => 'setTaxAmount',
        'total_amount' => 'setTotalAmount',
        'payments_allocations_total_amount' => 'setPaymentsAllocationsTotalAmount',
        'payments_allocations_total_discount' => 'setPaymentsAllocationsTotalDiscount',
        'total_paid' => 'setTotalPaid',
        'outstanding_amount' => 'setOutstandingAmount',
        'currency' => 'setCurrency',
        'exchange_rate' => 'setExchangeRate',
        'inverse_exchange_rate' => 'setInverseExchangeRate',
        'base_currency_net_amount' => 'setBaseCurrencyNetAmount',
        'base_currency_tax_amount' => 'setBaseCurrencyTaxAmount',
        'base_currency_total_amount' => 'setBaseCurrencyTotalAmount',
        'base_currency_outstanding_amount' => 'setBaseCurrencyOutstandingAmount',
        'status' => 'setStatus',
        'void_reason' => 'setVoidReason',
        'credit_note_lines' => 'setCreditNoteLines',
        'tax_analysis' => 'setTaxAnalysis',
        'detailed_tax_analysis' => 'setDetailedTaxAnalysis',
        'payments_allocations' => 'setPaymentsAllocations',
        'last_paid' => 'setLastPaid',
        'tax_address_region' => 'setTaxAddressRegion',
        'tax_reconciled' => 'setTaxReconciled',
        'migrated' => 'setMigrated',
        'tax_calculation_method' => 'setTaxCalculationMethod',
        'withholding_tax_rate' => 'setWithholdingTaxRate',
        'withholding_tax_amount' => 'setWithholdingTaxAmount',
        'base_currency_withholding_tax_amount' => 'setBaseCurrencyWithholdingTaxAmount'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'legacy_id' => 'getLegacyId',
        'id' => 'getId',
        'displayed_as' => 'getDisplayedAs',
        'path' => 'getPath',
        'created_at' => 'getCreatedAt',
        'updated_at' => 'getUpdatedAt',
        'links' => 'getLinks',
        'editable' => 'getEditable',
        'vat_reverse_charge' => 'getVatReverseCharge',
        'transaction' => 'getTransaction',
        'transaction_type' => 'getTransactionType',
        'postponed_accounting' => 'getPostponedAccounting',
        'import' => 'getImport',
        'vat_exempt_consignment' => 'getVatExemptConsignment',
        'deleted_at' => 'getDeletedAt',
        'is_cis' => 'getIsCis',
        'cis_applicable_amount' => 'getCisApplicableAmount',
        'base_currency_cis_applicable_amount' => 'getBaseCurrencyCisApplicableAmount',
        'total_after_cis_deduction' => 'getTotalAfterCisDeduction',
        'base_currency_total_after_cis_deduction' => 'getBaseCurrencyTotalAfterCisDeduction',
        'has_cis_labour' => 'getHasCisLabour',
        'has_cis_materials' => 'getHasCisMaterials',
        'contact' => 'getContact',
        'base_currency_total_itc_amount' => 'getBaseCurrencyTotalItcAmount',
        'total_itc_amount' => 'getTotalItcAmount',
        'base_currency_total_itr_amount' => 'getBaseCurrencyTotalItrAmount',
        'total_itr_amount' => 'getTotalItrAmount',
        'part_recoverable' => 'getPartRecoverable',
        'contact_name' => 'getContactName',
        'contact_reference' => 'getContactReference',
        'date' => 'getDate',
        'original_invoice_date' => 'getOriginalInvoiceDate',
        'reference' => 'getReference',
        'vendor_reference' => 'getVendorReference',
        'notes' => 'getNotes',
        'total_quantity' => 'getTotalQuantity',
        'net_amount' => 'getNetAmount',
        'tax_amount' => 'getTaxAmount',
        'total_amount' => 'getTotalAmount',
        'payments_allocations_total_amount' => 'getPaymentsAllocationsTotalAmount',
        'payments_allocations_total_discount' => 'getPaymentsAllocationsTotalDiscount',
        'total_paid' => 'getTotalPaid',
        'outstanding_amount' => 'getOutstandingAmount',
        'currency' => 'getCurrency',
        'exchange_rate' => 'getExchangeRate',
        'inverse_exchange_rate' => 'getInverseExchangeRate',
        'base_currency_net_amount' => 'getBaseCurrencyNetAmount',
        'base_currency_tax_amount' => 'getBaseCurrencyTaxAmount',
        'base_currency_total_amount' => 'getBaseCurrencyTotalAmount',
        'base_currency_outstanding_amount' => 'getBaseCurrencyOutstandingAmount',
        'status' => 'getStatus',
        'void_reason' => 'getVoidReason',
        'credit_note_lines' => 'getCreditNoteLines',
        'tax_analysis' => 'getTaxAnalysis',
        'detailed_tax_analysis' => 'getDetailedTaxAnalysis',
        'payments_allocations' => 'getPaymentsAllocations',
        'last_paid' => 'getLastPaid',
        'tax_address_region' => 'getTaxAddressRegion',
        'tax_reconciled' => 'getTaxReconciled',
        'migrated' => 'getMigrated',
        'tax_calculation_method' => 'getTaxCalculationMethod',
        'withholding_tax_rate' => 'getWithholdingTaxRate',
        'withholding_tax_amount' => 'getWithholdingTaxAmount',
        'base_currency_withholding_tax_amount' => 'getBaseCurrencyWithholdingTaxAmount'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['legacy_id'] = isset($data['legacy_id']) ? $data['legacy_id'] : null;
        $this->container['id'] = isset($data['id']) ? $data['id'] : null;
        $this->container['displayed_as'] = isset($data['displayed_as']) ? $data['displayed_as'] : null;
        $this->container['path'] = isset($data['path']) ? $data['path'] : null;
        $this->container['created_at'] = isset($data['created_at']) ? $data['created_at'] : null;
        $this->container['updated_at'] = isset($data['updated_at']) ? $data['updated_at'] : null;
        $this->container['links'] = isset($data['links']) ? $data['links'] : null;
        $this->container['editable'] = isset($data['editable']) ? $data['editable'] : null;
        $this->container['vat_reverse_charge'] = isset($data['vat_reverse_charge']) ? $data['vat_reverse_charge'] : null;
        $this->container['transaction'] = isset($data['transaction']) ? $data['transaction'] : null;
        $this->container['transaction_type'] = isset($data['transaction_type']) ? $data['transaction_type'] : null;
        $this->container['postponed_accounting'] = isset($data['postponed_accounting']) ? $data['postponed_accounting'] : null;
        $this->container['import'] = isset($data['import']) ? $data['import'] : null;
        $this->container['vat_exempt_consignment'] = isset($data['vat_exempt_consignment']) ? $data['vat_exempt_consignment'] : null;
        $this->container['deleted_at'] = isset($data['deleted_at']) ? $data['deleted_at'] : null;
        $this->container['is_cis'] = isset($data['is_cis']) ? $data['is_cis'] : null;
        $this->container['cis_applicable_amount'] = isset($data['cis_applicable_amount']) ? $data['cis_applicable_amount'] : null;
        $this->container['base_currency_cis_applicable_amount'] = isset($data['base_currency_cis_applicable_amount']) ? $data['base_currency_cis_applicable_amount'] : null;
        $this->container['total_after_cis_deduction'] = isset($data['total_after_cis_deduction']) ? $data['total_after_cis_deduction'] : null;
        $this->container['base_currency_total_after_cis_deduction'] = isset($data['base_currency_total_after_cis_deduction']) ? $data['base_currency_total_after_cis_deduction'] : null;
        $this->container['has_cis_labour'] = isset($data['has_cis_labour']) ? $data['has_cis_labour'] : null;
        $this->container['has_cis_materials'] = isset($data['has_cis_materials']) ? $data['has_cis_materials'] : null;
        $this->container['contact'] = isset($data['contact']) ? $data['contact'] : null;
        $this->container['base_currency_total_itc_amount'] = isset($data['base_currency_total_itc_amount']) ? $data['base_currency_total_itc_amount'] : null;
        $this->container['total_itc_amount'] = isset($data['total_itc_amount']) ? $data['total_itc_amount'] : null;
        $this->container['base_currency_total_itr_amount'] = isset($data['base_currency_total_itr_amount']) ? $data['base_currency_total_itr_amount'] : null;
        $this->container['total_itr_amount'] = isset($data['total_itr_amount']) ? $data['total_itr_amount'] : null;
        $this->container['part_recoverable'] = isset($data['part_recoverable']) ? $data['part_recoverable'] : null;
        $this->container['contact_name'] = isset($data['contact_name']) ? $data['contact_name'] : null;
        $this->container['contact_reference'] = isset($data['contact_reference']) ? $data['contact_reference'] : null;
        $this->container['date'] = isset($data['date']) ? $data['date'] : null;
        $this->container['original_invoice_date'] = isset($data['original_invoice_date']) ? $data['original_invoice_date'] : null;
        $this->container['reference'] = isset($data['reference']) ? $data['reference'] : null;
        $this->container['vendor_reference'] = isset($data['vendor_reference']) ? $data['vendor_reference'] : null;
        $this->container['notes'] = isset($data['notes']) ? $data['notes'] : null;
        $this->container['total_quantity'] = isset($data['total_quantity']) ? $data['total_quantity'] : null;
        $this->container['net_amount'] = isset($data['net_amount']) ? $data['net_amount'] : null;
        $this->container['tax_amount'] = isset($data['tax_amount']) ? $data['tax_amount'] : null;
        $this->container['total_amount'] = isset($data['total_amount']) ? $data['total_amount'] : null;
        $this->container['payments_allocations_total_amount'] = isset($data['payments_allocations_total_amount']) ? $data['payments_allocations_total_amount'] : null;
        $this->container['payments_allocations_total_discount'] = isset($data['payments_allocations_total_discount']) ? $data['payments_allocations_total_discount'] : null;
        $this->container['total_paid'] = isset($data['total_paid']) ? $data['total_paid'] : null;
        $this->container['outstanding_amount'] = isset($data['outstanding_amount']) ? $data['outstanding_amount'] : null;
        $this->container['currency'] = isset($data['currency']) ? $data['currency'] : null;
        $this->container['exchange_rate'] = isset($data['exchange_rate']) ? $data['exchange_rate'] : null;
        $this->container['inverse_exchange_rate'] = isset($data['inverse_exchange_rate']) ? $data['inverse_exchange_rate'] : null;
        $this->container['base_currency_net_amount'] = isset($data['base_currency_net_amount']) ? $data['base_currency_net_amount'] : null;
        $this->container['base_currency_tax_amount'] = isset($data['base_currency_tax_amount']) ? $data['base_currency_tax_amount'] : null;
        $this->container['base_currency_total_amount'] = isset($data['base_currency_total_amount']) ? $data['base_currency_total_amount'] : null;
        $this->container['base_currency_outstanding_amount'] = isset($data['base_currency_outstanding_amount']) ? $data['base_currency_outstanding_amount'] : null;
        $this->container['status'] = isset($data['status']) ? $data['status'] : null;
        $this->container['void_reason'] = isset($data['void_reason']) ? $data['void_reason'] : null;
        $this->container['credit_note_lines'] = isset($data['credit_note_lines']) ? $data['credit_note_lines'] : null;
        $this->container['tax_analysis'] = isset($data['tax_analysis']) ? $data['tax_analysis'] : null;
        $this->container['detailed_tax_analysis'] = isset($data['detailed_tax_analysis']) ? $data['detailed_tax_analysis'] : null;
        $this->container['payments_allocations'] = isset($data['payments_allocations']) ? $data['payments_allocations'] : null;
        $this->container['last_paid'] = isset($data['last_paid']) ? $data['last_paid'] : null;
        $this->container['tax_address_region'] = isset($data['tax_address_region']) ? $data['tax_address_region'] : null;
        $this->container['tax_reconciled'] = isset($data['tax_reconciled']) ? $data['tax_reconciled'] : null;
        $this->container['migrated'] = isset($data['migrated']) ? $data['migrated'] : null;
        $this->container['tax_calculation_method'] = isset($data['tax_calculation_method']) ? $data['tax_calculation_method'] : null;
        $this->container['withholding_tax_rate'] = isset($data['withholding_tax_rate']) ? $data['withholding_tax_rate'] : null;
        $this->container['withholding_tax_amount'] = isset($data['withholding_tax_amount']) ? $data['withholding_tax_amount'] : null;
        $this->container['base_currency_withholding_tax_amount'] = isset($data['base_currency_withholding_tax_amount']) ? $data['base_currency_withholding_tax_amount'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['contact_name']) && (mb_strlen($this->container['contact_name']) > 255)) {
            $invalidProperties[] = "invalid value for 'contact_name', the character length must be smaller than or equal to 255.";
        }

        if (!is_null($this->container['contact_reference']) && (mb_strlen($this->container['contact_reference']) > 255)) {
            $invalidProperties[] = "invalid value for 'contact_reference', the character length must be smaller than or equal to 255.";
        }

        if (!is_null($this->container['reference']) && (mb_strlen($this->container['reference']) > 25)) {
            $invalidProperties[] = "invalid value for 'reference', the character length must be smaller than or equal to 25.";
        }

        if (!is_null($this->container['vendor_reference']) && (mb_strlen($this->container['vendor_reference']) > 31)) {
            $invalidProperties[] = "invalid value for 'vendor_reference', the character length must be smaller than or equal to 31.";
        }

        if (!is_null($this->container['notes']) && (mb_strlen($this->container['notes']) > 2000)) {
            $invalidProperties[] = "invalid value for 'notes', the character length must be smaller than or equal to 2000.";
        }

        if (!is_null($this->container['void_reason']) && (mb_strlen($this->container['void_reason']) > 255)) {
            $invalidProperties[] = "invalid value for 'void_reason', the character length must be smaller than or equal to 255.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets legacy_id
     *
     * @return int
     */
    public function getLegacyId()
    {
        return $this->container['legacy_id'];
    }

    /**
     * Sets legacy_id
     *
     * @param int $legacy_id The legacy ID for the item
     *
     * @return $this
     */
    public function setLegacyId($legacy_id)
    {
        $this->container['legacy_id'] = $legacy_id;

        return $this;
    }

    /**
     * Gets id
     *
     * @return string
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string $id The unique identifier for the item
     *
     * @return $this
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets displayed_as
     *
     * @return string
     */
    public function getDisplayedAs()
    {
        return $this->container['displayed_as'];
    }

    /**
     * Sets displayed_as
     *
     * @param string $displayed_as The name of the resource
     *
     * @return $this
     */
    public function setDisplayedAs($displayed_as)
    {
        $this->container['displayed_as'] = $displayed_as;

        return $this;
    }

    /**
     * Gets path
     *
     * @return string
     */
    public function getPath()
    {
        return $this->container['path'];
    }

    /**
     * Sets path
     *
     * @param string $path The API path for the resource
     *
     * @return $this
     */
    public function setPath($path)
    {
        $this->container['path'] = $path;

        return $this;
    }

    /**
     * Gets created_at
     *
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->container['created_at'];
    }

    /**
     * Sets created_at
     *
     * @param \DateTime $created_at The datetime when the item was created
     *
     * @return $this
     */
    public function setCreatedAt($created_at)
    {
        $this->container['created_at'] = $created_at;

        return $this;
    }

    /**
     * Gets updated_at
     *
     * @return \DateTime
     */
    public function getUpdatedAt()
    {
        return $this->container['updated_at'];
    }

    /**
     * Sets updated_at
     *
     * @param \DateTime $updated_at The datetime when the item was last updated
     *
     * @return $this
     */
    public function setUpdatedAt($updated_at)
    {
        $this->container['updated_at'] = $updated_at;

        return $this;
    }

    /**
     * Gets links
     *
     * @return \Swagger\Client\Model\Link[]
     */
    public function getLinks()
    {
        return $this->container['links'];
    }

    /**
     * Sets links
     *
     * @param \Swagger\Client\Model\Link[] $links Links for the resource
     *
     * @return $this
     */
    public function setLinks($links)
    {
        $this->container['links'] = $links;

        return $this;
    }

    /**
     * Gets editable
     *
     * @return bool
     */
    public function getEditable()
    {
        return $this->container['editable'];
    }

    /**
     * Sets editable
     *
     * @param bool $editable Indicates whether artefact can be edited
     *
     * @return $this
     */
    public function setEditable($editable)
    {
        $this->container['editable'] = $editable;

        return $this;
    }

    /**
     * Gets vat_reverse_charge
     *
     * @return bool
     */
    public function getVatReverseCharge()
    {
        return $this->container['vat_reverse_charge'];
    }

    /**
     * Sets vat_reverse_charge
     *
     * @param bool $vat_reverse_charge Indicates whether Domestic Reverser Charge is applied to the artefact. Only used for a UK business.
     *
     * @return $this
     */
    public function setVatReverseCharge($vat_reverse_charge)
    {
        $this->container['vat_reverse_charge'] = $vat_reverse_charge;

        return $this;
    }

    /**
     * Gets transaction
     *
     * @return \Swagger\Client\Model\Transaction
     */
    public function getTransaction()
    {
        return $this->container['transaction'];
    }

    /**
     * Sets transaction
     *
     * @param \Swagger\Client\Model\Transaction $transaction The transaction record for the purchase credit note
     *
     * @return $this
     */
    public function setTransaction($transaction)
    {
        $this->container['transaction'] = $transaction;

        return $this;
    }

    /**
     * Gets transaction_type
     *
     * @return \Swagger\Client\Model\Base
     */
    public function getTransactionType()
    {
        return $this->container['transaction_type'];
    }

    /**
     * Sets transaction_type
     *
     * @param \Swagger\Client\Model\Base $transaction_type The transaction type of the item
     *
     * @return $this
     */
    public function setTransactionType($transaction_type)
    {
        $this->container['transaction_type'] = $transaction_type;

        return $this;
    }

    /**
     * Gets postponed_accounting
     *
     * @return bool
     */
    public function getPostponedAccounting()
    {
        return $this->container['postponed_accounting'];
    }

    /**
     * Sets postponed_accounting
     *
     * @param bool $postponed_accounting Indicates whether postponed accounting rules are applied to the artefact. Only used for UK and IE accounting businesses, where the vendor is flagged as importer
     *
     * @return $this
     */
    public function setPostponedAccounting($postponed_accounting)
    {
        $this->container['postponed_accounting'] = $postponed_accounting;

        return $this;
    }

    /**
     * Gets import
     *
     * @return bool
     */
    public function getImport()
    {
        return $this->container['import'];
    }

    /**
     * Sets import
     *
     * @param bool $import Indicates whether import rules are applied to the artefact. Only used for UK, IE, FR and ES Accounting businesses, where the vendor is flagged as importer.
     *
     * @return $this
     */
    public function setImport($import)
    {
        $this->container['import'] = $import;

        return $this;
    }

    /**
     * Gets vat_exempt_consignment
     *
     * @return bool
     */
    public function getVatExemptConsignment()
    {
        return $this->container['vat_exempt_consignment'];
    }

    /**
     * Sets vat_exempt_consignment
     *
     * @param bool $vat_exempt_consignment Indicates whether vat exempt import is applied to the artefact. Only used for a UK business, where the artefact has the consignment checkbox selected.
     *
     * @return $this
     */
    public function setVatExemptConsignment($vat_exempt_consignment)
    {
        $this->container['vat_exempt_consignment'] = $vat_exempt_consignment;

        return $this;
    }

    /**
     * Gets deleted_at
     *
     * @return \DateTime
     */
    public function getDeletedAt()
    {
        return $this->container['deleted_at'];
    }

    /**
     * Sets deleted_at
     *
     * @param \DateTime $deleted_at The datetime when the item was deleted
     *
     * @return $this
     */
    public function setDeletedAt($deleted_at)
    {
        $this->container['deleted_at'] = $deleted_at;

        return $this;
    }

    /**
     * Gets is_cis
     *
     * @return bool
     */
    public function getIsCis()
    {
        return $this->container['is_cis'];
    }

    /**
     * Sets is_cis
     *
     * @param bool $is_cis Identifies an artefact as CIS (Construction Industry Scheme) applicable - UK only
     *
     * @return $this
     */
    public function setIsCis($is_cis)
    {
        $this->container['is_cis'] = $is_cis;

        return $this;
    }

    /**
     * Gets cis_applicable_amount
     *
     * @return double
     */
    public function getCisApplicableAmount()
    {
        return $this->container['cis_applicable_amount'];
    }

    /**
     * Sets cis_applicable_amount
     *
     * @param double $cis_applicable_amount The total amount of CIS deductible labour - only applicable in UK
     *
     * @return $this
     */
    public function setCisApplicableAmount($cis_applicable_amount)
    {
        $this->container['cis_applicable_amount'] = $cis_applicable_amount;

        return $this;
    }

    /**
     * Gets base_currency_cis_applicable_amount
     *
     * @return double
     */
    public function getBaseCurrencyCisApplicableAmount()
    {
        return $this->container['base_currency_cis_applicable_amount'];
    }

    /**
     * Sets base_currency_cis_applicable_amount
     *
     * @param double $base_currency_cis_applicable_amount The total amount of CIS deductible labour in the base currency - only applicable in UK
     *
     * @return $this
     */
    public function setBaseCurrencyCisApplicableAmount($base_currency_cis_applicable_amount)
    {
        $this->container['base_currency_cis_applicable_amount'] = $base_currency_cis_applicable_amount;

        return $this;
    }

    /**
     * Gets total_after_cis_deduction
     *
     * @return double
     */
    public function getTotalAfterCisDeduction()
    {
        return $this->container['total_after_cis_deduction'];
    }

    /**
     * Sets total_after_cis_deduction
     *
     * @param double $total_after_cis_deduction The total of the artefact with the total of CIS deducted - only applicable in UK
     *
     * @return $this
     */
    public function setTotalAfterCisDeduction($total_after_cis_deduction)
    {
        $this->container['total_after_cis_deduction'] = $total_after_cis_deduction;

        return $this;
    }

    /**
     * Gets base_currency_total_after_cis_deduction
     *
     * @return double
     */
    public function getBaseCurrencyTotalAfterCisDeduction()
    {
        return $this->container['base_currency_total_after_cis_deduction'];
    }

    /**
     * Sets base_currency_total_after_cis_deduction
     *
     * @param double $base_currency_total_after_cis_deduction The total of the artefact with the total of CIS deducted in the base currency - only applicable in UK
     *
     * @return $this
     */
    public function setBaseCurrencyTotalAfterCisDeduction($base_currency_total_after_cis_deduction)
    {
        $this->container['base_currency_total_after_cis_deduction'] = $base_currency_total_after_cis_deduction;

        return $this;
    }

    /**
     * Gets has_cis_labour
     *
     * @return bool
     */
    public function getHasCisLabour()
    {
        return $this->container['has_cis_labour'];
    }

    /**
     * Sets has_cis_labour
     *
     * @param bool $has_cis_labour Identifies an artefact as having CIS Labour line items
     *
     * @return $this
     */
    public function setHasCisLabour($has_cis_labour)
    {
        $this->container['has_cis_labour'] = $has_cis_labour;

        return $this;
    }

    /**
     * Gets has_cis_materials
     *
     * @return bool
     */
    public function getHasCisMaterials()
    {
        return $this->container['has_cis_materials'];
    }

    /**
     * Sets has_cis_materials
     *
     * @param bool $has_cis_materials Identifies an artefact as having CIS Materials line items
     *
     * @return $this
     */
    public function setHasCisMaterials($has_cis_materials)
    {
        $this->container['has_cis_materials'] = $has_cis_materials;

        return $this;
    }

    /**
     * Gets contact
     *
     * @return \Swagger\Client\Model\Contact
     */
    public function getContact()
    {
        return $this->container['contact'];
    }

    /**
     * Sets contact
     *
     * @param \Swagger\Client\Model\Contact $contact The contact the purchase credit note relates to
     *
     * @return $this
     */
    public function setContact($contact)
    {
        $this->container['contact'] = $contact;

        return $this;
    }

    /**
     * Gets base_currency_total_itc_amount
     *
     * @return double
     */
    public function getBaseCurrencyTotalItcAmount()
    {
        return $this->container['base_currency_total_itc_amount'];
    }

    /**
     * Sets base_currency_total_itc_amount
     *
     * @param double $base_currency_total_itc_amount The total amount of input tax credit in base currency for the                      purchase credit note (Canada only)
     *
     * @return $this
     */
    public function setBaseCurrencyTotalItcAmount($base_currency_total_itc_amount)
    {
        $this->container['base_currency_total_itc_amount'] = $base_currency_total_itc_amount;

        return $this;
    }

    /**
     * Gets total_itc_amount
     *
     * @return double
     */
    public function getTotalItcAmount()
    {
        return $this->container['total_itc_amount'];
    }

    /**
     * Sets total_itc_amount
     *
     * @param double $total_itc_amount The total amount of input tax credit for the purchase credit note (Canada only)
     *
     * @return $this
     */
    public function setTotalItcAmount($total_itc_amount)
    {
        $this->container['total_itc_amount'] = $total_itc_amount;

        return $this;
    }

    /**
     * Gets base_currency_total_itr_amount
     *
     * @return double
     */
    public function getBaseCurrencyTotalItrAmount()
    {
        return $this->container['base_currency_total_itr_amount'];
    }

    /**
     * Sets base_currency_total_itr_amount
     *
     * @param double $base_currency_total_itr_amount The total amount of input tax refund in base currency for the                      purchase credit note (Canada only)
     *
     * @return $this
     */
    public function setBaseCurrencyTotalItrAmount($base_currency_total_itr_amount)
    {
        $this->container['base_currency_total_itr_amount'] = $base_currency_total_itr_amount;

        return $this;
    }

    /**
     * Gets total_itr_amount
     *
     * @return double
     */
    public function getTotalItrAmount()
    {
        return $this->container['total_itr_amount'];
    }

    /**
     * Sets total_itr_amount
     *
     * @param double $total_itr_amount The total amount of input tax refund for the purchase credit note (Canada only)
     *
     * @return $this
     */
    public function setTotalItrAmount($total_itr_amount)
    {
        $this->container['total_itr_amount'] = $total_itr_amount;

        return $this;
    }

    /**
     * Gets part_recoverable
     *
     * @return bool
     */
    public function getPartRecoverable()
    {
        return $this->container['part_recoverable'];
    }

    /**
     * Sets part_recoverable
     *
     * @param bool $part_recoverable Indicates if the purchase credit note is part recoverable or not (Canada only)
     *
     * @return $this
     */
    public function setPartRecoverable($part_recoverable)
    {
        $this->container['part_recoverable'] = $part_recoverable;

        return $this;
    }

    /**
     * Gets contact_name
     *
     * @return string
     */
    public function getContactName()
    {
        return $this->container['contact_name'];
    }

    /**
     * Sets contact_name
     *
     * @param string $contact_name The name of the contact when the credit note was created
     *
     * @return $this
     */
    public function setContactName($contact_name)
    {
        if (!is_null($contact_name) && (mb_strlen($contact_name) > 255)) {
            throw new \InvalidArgumentException('invalid length for $contact_name when calling PurchaseCreditNote., must be smaller than or equal to 255.');
        }

        $this->container['contact_name'] = $contact_name;

        return $this;
    }

    /**
     * Gets contact_reference
     *
     * @return string
     */
    public function getContactReference()
    {
        return $this->container['contact_reference'];
    }

    /**
     * Sets contact_reference
     *
     * @param string $contact_reference The reference of the contact when the credit note was created
     *
     * @return $this
     */
    public function setContactReference($contact_reference)
    {
        if (!is_null($contact_reference) && (mb_strlen($contact_reference) > 255)) {
            throw new \InvalidArgumentException('invalid length for $contact_reference when calling PurchaseCreditNote., must be smaller than or equal to 255.');
        }

        $this->container['contact_reference'] = $contact_reference;

        return $this;
    }

    /**
     * Gets date
     *
     * @return \DateTime
     */
    public function getDate()
    {
        return $this->container['date'];
    }

    /**
     * Sets date
     *
     * @param \DateTime $date The date of the credit note
     *
     * @return $this
     */
    public function setDate($date)
    {
        $this->container['date'] = $date;

        return $this;
    }

    /**
     * Gets original_invoice_date
     *
     * @return \DateTime
     */
    public function getOriginalInvoiceDate()
    {
        return $this->container['original_invoice_date'];
    }

    /**
     * Sets original_invoice_date
     *
     * @param \DateTime $original_invoice_date The date of the original invoice
     *
     * @return $this
     */
    public function setOriginalInvoiceDate($original_invoice_date)
    {
        $this->container['original_invoice_date'] = $original_invoice_date;

        return $this;
    }

    /**
     * Gets reference
     *
     * @return string
     */
    public function getReference()
    {
        return $this->container['reference'];
    }

    /**
     * Sets reference
     *
     * @param string $reference The reference for the credit note
     *
     * @return $this
     */
    public function setReference($reference)
    {
        if (!is_null($reference) && (mb_strlen($reference) > 25)) {
            throw new \InvalidArgumentException('invalid length for $reference when calling PurchaseCreditNote., must be smaller than or equal to 25.');
        }

        $this->container['reference'] = $reference;

        return $this;
    }

    /**
     * Gets vendor_reference
     *
     * @return string
     */
    public function getVendorReference()
    {
        return $this->container['vendor_reference'];
    }

    /**
     * Sets vendor_reference
     *
     * @param string $vendor_reference The vendor reference for the credit note
     *
     * @return $this
     */
    public function setVendorReference($vendor_reference)
    {
        if (!is_null($vendor_reference) && (mb_strlen($vendor_reference) > 31)) {
            throw new \InvalidArgumentException('invalid length for $vendor_reference when calling PurchaseCreditNote., must be smaller than or equal to 31.');
        }

        $this->container['vendor_reference'] = $vendor_reference;

        return $this;
    }

    /**
     * Gets notes
     *
     * @return string
     */
    public function getNotes()
    {
        return $this->container['notes'];
    }

    /**
     * Sets notes
     *
     * @param string $notes credit note notes
     *
     * @return $this
     */
    public function setNotes($notes)
    {
        if (!is_null($notes) && (mb_strlen($notes) > 2000)) {
            throw new \InvalidArgumentException('invalid length for $notes when calling PurchaseCreditNote., must be smaller than or equal to 2000.');
        }

        $this->container['notes'] = $notes;

        return $this;
    }

    /**
     * Gets total_quantity
     *
     * @return double
     */
    public function getTotalQuantity()
    {
        return $this->container['total_quantity'];
    }

    /**
     * Sets total_quantity
     *
     * @param double $total_quantity The total quantity of the credit note
     *
     * @return $this
     */
    public function setTotalQuantity($total_quantity)
    {
        $this->container['total_quantity'] = $total_quantity;

        return $this;
    }

    /**
     * Gets net_amount
     *
     * @return double
     */
    public function getNetAmount()
    {
        return $this->container['net_amount'];
    }

    /**
     * Sets net_amount
     *
     * @param double $net_amount The net amount of the credit note
     *
     * @return $this
     */
    public function setNetAmount($net_amount)
    {
        $this->container['net_amount'] = $net_amount;

        return $this;
    }

    /**
     * Gets tax_amount
     *
     * @return double
     */
    public function getTaxAmount()
    {
        return $this->container['tax_amount'];
    }

    /**
     * Sets tax_amount
     *
     * @param double $tax_amount The tax amount of the credit note
     *
     * @return $this
     */
    public function setTaxAmount($tax_amount)
    {
        $this->container['tax_amount'] = $tax_amount;

        return $this;
    }

    /**
     * Gets total_amount
     *
     * @return double
     */
    public function getTotalAmount()
    {
        return $this->container['total_amount'];
    }

    /**
     * Sets total_amount
     *
     * @param double $total_amount The total amount of the credit note
     *
     * @return $this
     */
    public function setTotalAmount($total_amount)
    {
        $this->container['total_amount'] = $total_amount;

        return $this;
    }

    /**
     * Gets payments_allocations_total_amount
     *
     * @return double
     */
    public function getPaymentsAllocationsTotalAmount()
    {
        return $this->container['payments_allocations_total_amount'];
    }

    /**
     * Sets payments_allocations_total_amount
     *
     * @param double $payments_allocations_total_amount The total amount of all payments and allocations
     *
     * @return $this
     */
    public function setPaymentsAllocationsTotalAmount($payments_allocations_total_amount)
    {
        $this->container['payments_allocations_total_amount'] = $payments_allocations_total_amount;

        return $this;
    }

    /**
     * Gets payments_allocations_total_discount
     *
     * @return double
     */
    public function getPaymentsAllocationsTotalDiscount()
    {
        return $this->container['payments_allocations_total_discount'];
    }

    /**
     * Sets payments_allocations_total_discount
     *
     * @param double $payments_allocations_total_discount The total discount of all payments and allocations
     *
     * @return $this
     */
    public function setPaymentsAllocationsTotalDiscount($payments_allocations_total_discount)
    {
        $this->container['payments_allocations_total_discount'] = $payments_allocations_total_discount;

        return $this;
    }

    /**
     * Gets total_paid
     *
     * @return double
     */
    public function getTotalPaid()
    {
        return $this->container['total_paid'];
    }

    /**
     * Sets total_paid
     *
     * @param double $total_paid The total paid amount of the credit note including any payments, allocations and discounts
     *
     * @return $this
     */
    public function setTotalPaid($total_paid)
    {
        $this->container['total_paid'] = $total_paid;

        return $this;
    }

    /**
     * Gets outstanding_amount
     *
     * @return double
     */
    public function getOutstandingAmount()
    {
        return $this->container['outstanding_amount'];
    }

    /**
     * Sets outstanding_amount
     *
     * @param double $outstanding_amount The outstanding amount of the credit note
     *
     * @return $this
     */
    public function setOutstandingAmount($outstanding_amount)
    {
        $this->container['outstanding_amount'] = $outstanding_amount;

        return $this;
    }

    /**
     * Gets currency
     *
     * @return \Swagger\Client\Model\Base
     */
    public function getCurrency()
    {
        return $this->container['currency'];
    }

    /**
     * Sets currency
     *
     * @param \Swagger\Client\Model\Base $currency The currency for the credit note
     *
     * @return $this
     */
    public function setCurrency($currency)
    {
        $this->container['currency'] = $currency;

        return $this;
    }

    /**
     * Gets exchange_rate
     *
     * @return double
     */
    public function getExchangeRate()
    {
        return $this->container['exchange_rate'];
    }

    /**
     * Sets exchange_rate
     *
     * @param double $exchange_rate The exchange rate for the credit note
     *
     * @return $this
     */
    public function setExchangeRate($exchange_rate)
    {
        $this->container['exchange_rate'] = $exchange_rate;

        return $this;
    }

    /**
     * Gets inverse_exchange_rate
     *
     * @return string
     */
    public function getInverseExchangeRate()
    {
        return $this->container['inverse_exchange_rate'];
    }

    /**
     * Sets inverse_exchange_rate
     *
     * @param string $inverse_exchange_rate The inverse exchange rate for the credit note
     *
     * @return $this
     */
    public function setInverseExchangeRate($inverse_exchange_rate)
    {
        $this->container['inverse_exchange_rate'] = $inverse_exchange_rate;

        return $this;
    }

    /**
     * Gets base_currency_net_amount
     *
     * @return double
     */
    public function getBaseCurrencyNetAmount()
    {
        return $this->container['base_currency_net_amount'];
    }

    /**
     * Sets base_currency_net_amount
     *
     * @param double $base_currency_net_amount The net amount of the credit note in base currency
     *
     * @return $this
     */
    public function setBaseCurrencyNetAmount($base_currency_net_amount)
    {
        $this->container['base_currency_net_amount'] = $base_currency_net_amount;

        return $this;
    }

    /**
     * Gets base_currency_tax_amount
     *
     * @return double
     */
    public function getBaseCurrencyTaxAmount()
    {
        return $this->container['base_currency_tax_amount'];
    }

    /**
     * Sets base_currency_tax_amount
     *
     * @param double $base_currency_tax_amount The tax amount of the credit note in base currency
     *
     * @return $this
     */
    public function setBaseCurrencyTaxAmount($base_currency_tax_amount)
    {
        $this->container['base_currency_tax_amount'] = $base_currency_tax_amount;

        return $this;
    }

    /**
     * Gets base_currency_total_amount
     *
     * @return double
     */
    public function getBaseCurrencyTotalAmount()
    {
        return $this->container['base_currency_total_amount'];
    }

    /**
     * Sets base_currency_total_amount
     *
     * @param double $base_currency_total_amount The total amount of the credit note in base currency
     *
     * @return $this
     */
    public function setBaseCurrencyTotalAmount($base_currency_total_amount)
    {
        $this->container['base_currency_total_amount'] = $base_currency_total_amount;

        return $this;
    }

    /**
     * Gets base_currency_outstanding_amount
     *
     * @return double
     */
    public function getBaseCurrencyOutstandingAmount()
    {
        return $this->container['base_currency_outstanding_amount'];
    }

    /**
     * Sets base_currency_outstanding_amount
     *
     * @param double $base_currency_outstanding_amount The outstanding amount of the credit note in base currency
     *
     * @return $this
     */
    public function setBaseCurrencyOutstandingAmount($base_currency_outstanding_amount)
    {
        $this->container['base_currency_outstanding_amount'] = $base_currency_outstanding_amount;

        return $this;
    }

    /**
     * Gets status
     *
     * @return \Swagger\Client\Model\Base
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param \Swagger\Client\Model\Base $status The status of the credit note
     *
     * @return $this
     */
    public function setStatus($status)
    {
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets void_reason
     *
     * @return string
     */
    public function getVoidReason()
    {
        return $this->container['void_reason'];
    }

    /**
     * Sets void_reason
     *
     * @param string $void_reason The reason the credit note was voided
     *
     * @return $this
     */
    public function setVoidReason($void_reason)
    {
        if (!is_null($void_reason) && (mb_strlen($void_reason) > 255)) {
            throw new \InvalidArgumentException('invalid length for $void_reason when calling PurchaseCreditNote., must be smaller than or equal to 255.');
        }

        $this->container['void_reason'] = $void_reason;

        return $this;
    }

    /**
     * Gets credit_note_lines
     *
     * @return \Swagger\Client\Model\PurchaseCreditNoteLineItem[]
     */
    public function getCreditNoteLines()
    {
        return $this->container['credit_note_lines'];
    }

    /**
     * Sets credit_note_lines
     *
     * @param \Swagger\Client\Model\PurchaseCreditNoteLineItem[] $credit_note_lines The credit note lines of the credit note
     *
     * @return $this
     */
    public function setCreditNoteLines($credit_note_lines)
    {
        $this->container['credit_note_lines'] = $credit_note_lines;

        return $this;
    }

    /**
     * Gets tax_analysis
     *
     * @return \Swagger\Client\Model\ArtefactTaxAnalysis[]
     */
    public function getTaxAnalysis()
    {
        return $this->container['tax_analysis'];
    }

    /**
     * Sets tax_analysis
     *
     * @param \Swagger\Client\Model\ArtefactTaxAnalysis[] $tax_analysis The credit note tax analysis
     *
     * @return $this
     */
    public function setTaxAnalysis($tax_analysis)
    {
        $this->container['tax_analysis'] = $tax_analysis;

        return $this;
    }

    /**
     * Gets detailed_tax_analysis
     *
     * @return \Swagger\Client\Model\ArtefactDetailedTaxAnalysis
     */
    public function getDetailedTaxAnalysis()
    {
        return $this->container['detailed_tax_analysis'];
    }

    /**
     * Sets detailed_tax_analysis
     *
     * @param \Swagger\Client\Model\ArtefactDetailedTaxAnalysis $detailed_tax_analysis detailed_tax_analysis
     *
     * @return $this
     */
    public function setDetailedTaxAnalysis($detailed_tax_analysis)
    {
        $this->container['detailed_tax_analysis'] = $detailed_tax_analysis;

        return $this;
    }

    /**
     * Gets payments_allocations
     *
     * @return \Swagger\Client\Model\PaymentAllocation[]
     */
    public function getPaymentsAllocations()
    {
        return $this->container['payments_allocations'];
    }

    /**
     * Sets payments_allocations
     *
     * @param \Swagger\Client\Model\PaymentAllocation[] $payments_allocations The associated payments and allocations
     *
     * @return $this
     */
    public function setPaymentsAllocations($payments_allocations)
    {
        $this->container['payments_allocations'] = $payments_allocations;

        return $this;
    }

    /**
     * Gets last_paid
     *
     * @return \DateTime
     */
    public function getLastPaid()
    {
        return $this->container['last_paid'];
    }

    /**
     * Sets last_paid
     *
     * @param \DateTime $last_paid The date of the last payment
     *
     * @return $this
     */
    public function setLastPaid($last_paid)
    {
        $this->container['last_paid'] = $last_paid;

        return $this;
    }

    /**
     * Gets tax_address_region
     *
     * @return \Swagger\Client\Model\Base
     */
    public function getTaxAddressRegion()
    {
        return $this->container['tax_address_region'];
    }

    /**
     * Sets tax_address_region
     *
     * @param \Swagger\Client\Model\Base $tax_address_region The address region for tax purposes (Canada only)
     *
     * @return $this
     */
    public function setTaxAddressRegion($tax_address_region)
    {
        $this->container['tax_address_region'] = $tax_address_region;

        return $this;
    }

    /**
     * Gets tax_reconciled
     *
     * @return bool
     */
    public function getTaxReconciled()
    {
        return $this->container['tax_reconciled'];
    }

    /**
     * Sets tax_reconciled
     *
     * @param bool $tax_reconciled Indicates if the purchase credit note is tax reconciled or not.
     *
     * @return $this
     */
    public function setTaxReconciled($tax_reconciled)
    {
        $this->container['tax_reconciled'] = $tax_reconciled;

        return $this;
    }

    /**
     * Gets migrated
     *
     * @return bool
     */
    public function getMigrated()
    {
        return $this->container['migrated'];
    }

    /**
     * Sets migrated
     *
     * @param bool $migrated Indicates if the purchase credit note was migrated from another system.
     *
     * @return $this
     */
    public function setMigrated($migrated)
    {
        $this->container['migrated'] = $migrated;

        return $this;
    }

    /**
     * Gets tax_calculation_method
     *
     * @return string
     */
    public function getTaxCalculationMethod()
    {
        return $this->container['tax_calculation_method'];
    }

    /**
     * Sets tax_calculation_method
     *
     * @param string $tax_calculation_method The tax calculation method, if applicable, for this purchase credit note, returns invoice or cash.
     *
     * @return $this
     */
    public function setTaxCalculationMethod($tax_calculation_method)
    {
        $this->container['tax_calculation_method'] = $tax_calculation_method;

        return $this;
    }

    /**
     * Gets withholding_tax_rate
     *
     * @return double
     */
    public function getWithholdingTaxRate()
    {
        return $this->container['withholding_tax_rate'];
    }

    /**
     * Sets withholding_tax_rate
     *
     * @param double $withholding_tax_rate The withheld Tax Rate - only applicable in UK (CIS subcontractor tax rate)
     *
     * @return $this
     */
    public function setWithholdingTaxRate($withholding_tax_rate)
    {
        $this->container['withholding_tax_rate'] = $withholding_tax_rate;

        return $this;
    }

    /**
     * Gets withholding_tax_amount
     *
     * @return double
     */
    public function getWithholdingTaxAmount()
    {
        return $this->container['withholding_tax_amount'];
    }

    /**
     * Sets withholding_tax_amount
     *
     * @param double $withholding_tax_amount The withheld Tax Amount - only applicable in UK (CIS subcontractor tax)
     *
     * @return $this
     */
    public function setWithholdingTaxAmount($withholding_tax_amount)
    {
        $this->container['withholding_tax_amount'] = $withholding_tax_amount;

        return $this;
    }

    /**
     * Gets base_currency_withholding_tax_amount
     *
     * @return double
     */
    public function getBaseCurrencyWithholdingTaxAmount()
    {
        return $this->container['base_currency_withholding_tax_amount'];
    }

    /**
     * Sets base_currency_withholding_tax_amount
     *
     * @param double $base_currency_withholding_tax_amount The withheld Tax Amount in the base currency - only applicable in UK (CIS subcontractor tax)
     *
     * @return $this
     */
    public function setBaseCurrencyWithholdingTaxAmount($base_currency_withholding_tax_amount)
    {
        $this->container['base_currency_withholding_tax_amount'] = $base_currency_withholding_tax_amount;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


