<?php
/**
 * ContactAllocationsApi
 * PHP version 8.1
 *
 * @package  SynergiTech\Sage
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Sage One - Accounts - v3 UKI
 *
 * Documentation of the Sage Business Cloud Accounting API.
 *
 * The version of the OpenAPI document: 1.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace SynergiTech\Sage\Api;

use InvalidArgumentException;
use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use GuzzleHttp\Promise\PromiseInterface;
use SynergiTech\Sage\ApiException;
use SynergiTech\Sage\Configuration;
use SynergiTech\Sage\HeaderSelector;
use SynergiTech\Sage\ObjectSerializer;

/**
 * ContactAllocationsApi Class Doc Comment
 *
 * @package  SynergiTech\Sage
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ContactAllocationsApi
{
    /**
     * @var ClientInterface
     */
    protected ClientInterface $client;

    /**
     * @var Configuration
     */
    protected Configuration $config;

    /**
     * @var HeaderSelector
     */
    protected HeaderSelector $headerSelector;

    /**
     * @var int Host index
     */
    protected int $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'deleteContactAllocationsKey' => [
            'application/json',
        ],
        'getContactAllocations' => [
            'application/json',
        ],
        'getContactAllocationsKey' => [
            'application/json',
        ],
        'postContactAllocations' => [
            'application/json',
        ],
        'putContactAllocationsKey' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface|null $client
     * @param Configuration|null   $config
     * @param HeaderSelector|null  $selector
     * @param int                  $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex(int $hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex(): int
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig(): Configuration
    {
        return $this->config;
    }

    /**
     * Operation deleteContactAllocationsKey
     *
     * Deletes a Contact Allocation
     *
     * @param  string $key The Contact Allocation Key. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteContactAllocationsKey'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return void
     */
    public function deleteContactAllocationsKey(
        string $key,
        string $contentType = self::contentTypes['deleteContactAllocationsKey'][0]
    ): void
    {
        $this->deleteContactAllocationsKeyWithHttpInfo($key, $contentType);
    }

    /**
     * Operation deleteContactAllocationsKeyWithHttpInfo
     *
     * Deletes a Contact Allocation
     *
     * @param  string $key The Contact Allocation Key. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteContactAllocationsKey'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function deleteContactAllocationsKeyWithHttpInfo(
        string $key,
        string $contentType = self::contentTypes['deleteContactAllocationsKey'][0]
    ): array
    {
        $request = $this->deleteContactAllocationsKeyRequest($key, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation deleteContactAllocationsKeyAsync
     *
     * Deletes a Contact Allocation
     *
     * @param  string $key The Contact Allocation Key. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteContactAllocationsKey'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function deleteContactAllocationsKeyAsync(
        string $key,
        string $contentType = self::contentTypes['deleteContactAllocationsKey'][0]
    ): PromiseInterface
    {
        return $this->deleteContactAllocationsKeyAsyncWithHttpInfo($key, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation deleteContactAllocationsKeyAsyncWithHttpInfo
     *
     * Deletes a Contact Allocation
     *
     * @param  string $key The Contact Allocation Key. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteContactAllocationsKey'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function deleteContactAllocationsKeyAsyncWithHttpInfo(
        string $key,
        string $contentType = self::contentTypes['deleteContactAllocationsKey'][0]
    ): PromiseInterface
    {
        $returnType = '';
        $request = $this->deleteContactAllocationsKeyRequest($key, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'deleteContactAllocationsKey'
     *
     * @param  string $key The Contact Allocation Key. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteContactAllocationsKey'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function deleteContactAllocationsKeyRequest(
        string $key,
        string $contentType = self::contentTypes['deleteContactAllocationsKey'][0]
    ): Request
    {

        // verify the required parameter 'key' is set
        if ($key === null || (is_array($key) && count($key) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $key when calling deleteContactAllocationsKey'
            );
        }


        $resourcePath = '/contact_allocations/{key}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($key !== null) {
            $resourcePath = str_replace(
                '{' . 'key' . '}',
                ObjectSerializer::toPathValue($key),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            [],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('subscription-key');
        if ($apiKey !== null) {
            $queryParams['subscription-key'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Ocp-Apim-Subscription-Key');
        if ($apiKey !== null) {
            $headers['Ocp-Apim-Subscription-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'DELETE',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getContactAllocations
     *
     * Returns all Contact Allocations
     *
     * @param  string|null $contactId Use this to filter by contact id (optional)
     * @param  string|null $transactionTypeId Use this to filter by transaction type id (optional)
     * @param  \DateTime|null $updatedOrCreatedSince Format - date-time (as date-time in RFC3339). Use this to limit the response to Allocations changed since a given date (format: YYYY-MM-DDT(+|-)hh:mm) or date-time (format: YYYY-MM-DDThh:mm:ss(+|-)hh:mm). Inclusive of the passed timestamp. (optional)
     * @param  \DateTime|null $deletedSince Format - date-time (as date-time in RFC3339). Use this to limit the response to Allocations deleted since a given date (format: YYYY-MM-DDT(+|-)hh:mm) or date-time (format: YYYY-MM-DDThh:mm:ss(+|-)hh:mm). Not inclusive of the passed timestamp. (optional)
     * @param  bool|null $showLegacyId Display the legacy_id for the Allocations. (optional)
     * @param  int|null $itemsPerPage Format - int32. Returns the given number of Allocations per request. (optional, default to 20)
     * @param  int|null $page Format - int32. Go to specific page of Allocations (optional, default to 1)
     * @param  string|null $attributes Specify the attributes that you want to expose for the Allocations (expose all attributes with &#39;all&#39;). These are in addition to the base attributes (name, path) (optional)
     * @param  string|null $sort Order by a given attribute (required) and direction (optional; &#x60;asc&#x60; or &#x60;desc&#x60;; defaults to &#x60;asc&#x60;). Available attributes are: created_at, updated_at, date  Example: &#x60;sort&#x3D;created_at&#x60; or &#x60;sort&#x3D;created_at:desc&#x60; (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getContactAllocations'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return \SynergiTech\Sage\Model\ContactAllocation[]
     */
    public function getContactAllocations(
        ?string $contactId = null,
        ?string $transactionTypeId = null,
        ?\DateTime $updatedOrCreatedSince = null,
        ?\DateTime $deletedSince = null,
        ?bool $showLegacyId = null,
        ?int $itemsPerPage = 20,
        ?int $page = 1,
        ?string $attributes = null,
        ?string $sort = null,
        string $contentType = self::contentTypes['getContactAllocations'][0]
    ): array
    {
        list($response) = $this->getContactAllocationsWithHttpInfo($contactId, $transactionTypeId, $updatedOrCreatedSince, $deletedSince, $showLegacyId, $itemsPerPage, $page, $attributes, $sort, $contentType);
        return $response;
    }

    /**
     * Operation getContactAllocationsWithHttpInfo
     *
     * Returns all Contact Allocations
     *
     * @param  string|null $contactId Use this to filter by contact id (optional)
     * @param  string|null $transactionTypeId Use this to filter by transaction type id (optional)
     * @param  \DateTime|null $updatedOrCreatedSince Format - date-time (as date-time in RFC3339). Use this to limit the response to Allocations changed since a given date (format: YYYY-MM-DDT(+|-)hh:mm) or date-time (format: YYYY-MM-DDThh:mm:ss(+|-)hh:mm). Inclusive of the passed timestamp. (optional)
     * @param  \DateTime|null $deletedSince Format - date-time (as date-time in RFC3339). Use this to limit the response to Allocations deleted since a given date (format: YYYY-MM-DDT(+|-)hh:mm) or date-time (format: YYYY-MM-DDThh:mm:ss(+|-)hh:mm). Not inclusive of the passed timestamp. (optional)
     * @param  bool|null $showLegacyId Display the legacy_id for the Allocations. (optional)
     * @param  int|null $itemsPerPage Format - int32. Returns the given number of Allocations per request. (optional, default to 20)
     * @param  int|null $page Format - int32. Go to specific page of Allocations (optional, default to 1)
     * @param  string|null $attributes Specify the attributes that you want to expose for the Allocations (expose all attributes with &#39;all&#39;). These are in addition to the base attributes (name, path) (optional)
     * @param  string|null $sort Order by a given attribute (required) and direction (optional; &#x60;asc&#x60; or &#x60;desc&#x60;; defaults to &#x60;asc&#x60;). Available attributes are: created_at, updated_at, date  Example: &#x60;sort&#x3D;created_at&#x60; or &#x60;sort&#x3D;created_at:desc&#x60; (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getContactAllocations'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array of \SynergiTech\Sage\Model\ContactAllocation[], HTTP status code, HTTP response headers (array of strings)
     */
    public function getContactAllocationsWithHttpInfo(
        ?string $contactId = null,
        ?string $transactionTypeId = null,
        ?\DateTime $updatedOrCreatedSince = null,
        ?\DateTime $deletedSince = null,
        ?bool $showLegacyId = null,
        ?int $itemsPerPage = 20,
        ?int $page = 1,
        ?string $attributes = null,
        ?string $sort = null,
        string $contentType = self::contentTypes['getContactAllocations'][0]
    ): array
    {
        $request = $this->getContactAllocationsRequest($contactId, $transactionTypeId, $updatedOrCreatedSince, $deletedSince, $showLegacyId, $itemsPerPage, $page, $attributes, $sort, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    if (in_array('\SynergiTech\Sage\Model\ContactAllocation[]', ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\SynergiTech\Sage\Model\ContactAllocation[]' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\SynergiTech\Sage\Model\ContactAllocation[]', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            $returnType = '\SynergiTech\Sage\Model\ContactAllocation[]';
            if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\SynergiTech\Sage\Model\ContactAllocation[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getContactAllocationsAsync
     *
     * Returns all Contact Allocations
     *
     * @param  string|null $contactId Use this to filter by contact id (optional)
     * @param  string|null $transactionTypeId Use this to filter by transaction type id (optional)
     * @param  \DateTime|null $updatedOrCreatedSince Format - date-time (as date-time in RFC3339). Use this to limit the response to Allocations changed since a given date (format: YYYY-MM-DDT(+|-)hh:mm) or date-time (format: YYYY-MM-DDThh:mm:ss(+|-)hh:mm). Inclusive of the passed timestamp. (optional)
     * @param  \DateTime|null $deletedSince Format - date-time (as date-time in RFC3339). Use this to limit the response to Allocations deleted since a given date (format: YYYY-MM-DDT(+|-)hh:mm) or date-time (format: YYYY-MM-DDThh:mm:ss(+|-)hh:mm). Not inclusive of the passed timestamp. (optional)
     * @param  bool|null $showLegacyId Display the legacy_id for the Allocations. (optional)
     * @param  int|null $itemsPerPage Format - int32. Returns the given number of Allocations per request. (optional, default to 20)
     * @param  int|null $page Format - int32. Go to specific page of Allocations (optional, default to 1)
     * @param  string|null $attributes Specify the attributes that you want to expose for the Allocations (expose all attributes with &#39;all&#39;). These are in addition to the base attributes (name, path) (optional)
     * @param  string|null $sort Order by a given attribute (required) and direction (optional; &#x60;asc&#x60; or &#x60;desc&#x60;; defaults to &#x60;asc&#x60;). Available attributes are: created_at, updated_at, date  Example: &#x60;sort&#x3D;created_at&#x60; or &#x60;sort&#x3D;created_at:desc&#x60; (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getContactAllocations'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function getContactAllocationsAsync(
        ?string $contactId = null,
        ?string $transactionTypeId = null,
        ?\DateTime $updatedOrCreatedSince = null,
        ?\DateTime $deletedSince = null,
        ?bool $showLegacyId = null,
        ?int $itemsPerPage = 20,
        ?int $page = 1,
        ?string $attributes = null,
        ?string $sort = null,
        string $contentType = self::contentTypes['getContactAllocations'][0]
    ): PromiseInterface
    {
        return $this->getContactAllocationsAsyncWithHttpInfo($contactId, $transactionTypeId, $updatedOrCreatedSince, $deletedSince, $showLegacyId, $itemsPerPage, $page, $attributes, $sort, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getContactAllocationsAsyncWithHttpInfo
     *
     * Returns all Contact Allocations
     *
     * @param  string|null $contactId Use this to filter by contact id (optional)
     * @param  string|null $transactionTypeId Use this to filter by transaction type id (optional)
     * @param  \DateTime|null $updatedOrCreatedSince Format - date-time (as date-time in RFC3339). Use this to limit the response to Allocations changed since a given date (format: YYYY-MM-DDT(+|-)hh:mm) or date-time (format: YYYY-MM-DDThh:mm:ss(+|-)hh:mm). Inclusive of the passed timestamp. (optional)
     * @param  \DateTime|null $deletedSince Format - date-time (as date-time in RFC3339). Use this to limit the response to Allocations deleted since a given date (format: YYYY-MM-DDT(+|-)hh:mm) or date-time (format: YYYY-MM-DDThh:mm:ss(+|-)hh:mm). Not inclusive of the passed timestamp. (optional)
     * @param  bool|null $showLegacyId Display the legacy_id for the Allocations. (optional)
     * @param  int|null $itemsPerPage Format - int32. Returns the given number of Allocations per request. (optional, default to 20)
     * @param  int|null $page Format - int32. Go to specific page of Allocations (optional, default to 1)
     * @param  string|null $attributes Specify the attributes that you want to expose for the Allocations (expose all attributes with &#39;all&#39;). These are in addition to the base attributes (name, path) (optional)
     * @param  string|null $sort Order by a given attribute (required) and direction (optional; &#x60;asc&#x60; or &#x60;desc&#x60;; defaults to &#x60;asc&#x60;). Available attributes are: created_at, updated_at, date  Example: &#x60;sort&#x3D;created_at&#x60; or &#x60;sort&#x3D;created_at:desc&#x60; (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getContactAllocations'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function getContactAllocationsAsyncWithHttpInfo(
        ?string $contactId = null,
        ?string $transactionTypeId = null,
        ?\DateTime $updatedOrCreatedSince = null,
        ?\DateTime $deletedSince = null,
        ?bool $showLegacyId = null,
        ?int $itemsPerPage = 20,
        ?int $page = 1,
        ?string $attributes = null,
        ?string $sort = null,
        string $contentType = self::contentTypes['getContactAllocations'][0]
    ): PromiseInterface
    {
        $returnType = '\SynergiTech\Sage\Model\ContactAllocation[]';
        $request = $this->getContactAllocationsRequest($contactId, $transactionTypeId, $updatedOrCreatedSince, $deletedSince, $showLegacyId, $itemsPerPage, $page, $attributes, $sort, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getContactAllocations'
     *
     * @param  string|null $contactId Use this to filter by contact id (optional)
     * @param  string|null $transactionTypeId Use this to filter by transaction type id (optional)
     * @param  \DateTime|null $updatedOrCreatedSince Format - date-time (as date-time in RFC3339). Use this to limit the response to Allocations changed since a given date (format: YYYY-MM-DDT(+|-)hh:mm) or date-time (format: YYYY-MM-DDThh:mm:ss(+|-)hh:mm). Inclusive of the passed timestamp. (optional)
     * @param  \DateTime|null $deletedSince Format - date-time (as date-time in RFC3339). Use this to limit the response to Allocations deleted since a given date (format: YYYY-MM-DDT(+|-)hh:mm) or date-time (format: YYYY-MM-DDThh:mm:ss(+|-)hh:mm). Not inclusive of the passed timestamp. (optional)
     * @param  bool|null $showLegacyId Display the legacy_id for the Allocations. (optional)
     * @param  int|null $itemsPerPage Format - int32. Returns the given number of Allocations per request. (optional, default to 20)
     * @param  int|null $page Format - int32. Go to specific page of Allocations (optional, default to 1)
     * @param  string|null $attributes Specify the attributes that you want to expose for the Allocations (expose all attributes with &#39;all&#39;). These are in addition to the base attributes (name, path) (optional)
     * @param  string|null $sort Order by a given attribute (required) and direction (optional; &#x60;asc&#x60; or &#x60;desc&#x60;; defaults to &#x60;asc&#x60;). Available attributes are: created_at, updated_at, date  Example: &#x60;sort&#x3D;created_at&#x60; or &#x60;sort&#x3D;created_at:desc&#x60; (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getContactAllocations'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getContactAllocationsRequest(
        ?string $contactId = null,
        ?string $transactionTypeId = null,
        ?\DateTime $updatedOrCreatedSince = null,
        ?\DateTime $deletedSince = null,
        ?bool $showLegacyId = null,
        ?int $itemsPerPage = 20,
        ?int $page = 1,
        ?string $attributes = null,
        ?string $sort = null,
        string $contentType = self::contentTypes['getContactAllocations'][0]
    ): Request
    {






        if ($itemsPerPage !== null && $itemsPerPage > 200) {
            throw new InvalidArgumentException('invalid value for "$itemsPerPage" when calling ContactAllocationsApi.getContactAllocations, must be smaller than or equal to 200.');
        }
        if ($itemsPerPage !== null && $itemsPerPage < 1) {
            throw new InvalidArgumentException('invalid value for "$itemsPerPage" when calling ContactAllocationsApi.getContactAllocations, must be bigger than or equal to 1.');
        }
        




        $resourcePath = '/contact_allocations';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $contactId,
            'contact_id', // param base name
            'string', // openApiType
            '', // style
            false, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $transactionTypeId,
            'transaction_type_id', // param base name
            'string', // openApiType
            '', // style
            false, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $updatedOrCreatedSince,
            'updated_or_created_since', // param base name
            'string', // openApiType
            '', // style
            false, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $deletedSince,
            'deleted_since', // param base name
            'string', // openApiType
            '', // style
            false, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $showLegacyId,
            'show_legacy_id', // param base name
            'boolean', // openApiType
            '', // style
            false, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $itemsPerPage,
            'items_per_page', // param base name
            'integer', // openApiType
            '', // style
            false, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page,
            'page', // param base name
            'integer', // openApiType
            '', // style
            false, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $attributes,
            'attributes', // param base name
            'string', // openApiType
            '', // style
            false, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $sort,
            'sort', // param base name
            'string', // openApiType
            '', // style
            false, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('subscription-key');
        if ($apiKey !== null) {
            $queryParams['subscription-key'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Ocp-Apim-Subscription-Key');
        if ($apiKey !== null) {
            $headers['Ocp-Apim-Subscription-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getContactAllocationsKey
     *
     * Returns a Contact Allocation
     *
     * @param  string $key The Contact Allocation Key. (required)
     * @param  string|null $attributes Specify the attributes that you want to expose for the Allocation (expose all attributes with &#39;all&#39;). These are in addition to the base attributes (name, path) (optional)
     * @param  bool|null $showLegacyId Display the legacy_id for the Allocation. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getContactAllocationsKey'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return \SynergiTech\Sage\Model\ContactAllocation
     */
    public function getContactAllocationsKey(
        string $key,
        ?string $attributes = null,
        ?bool $showLegacyId = null,
        string $contentType = self::contentTypes['getContactAllocationsKey'][0]
    ): \SynergiTech\Sage\Model\ContactAllocation
    {
        list($response) = $this->getContactAllocationsKeyWithHttpInfo($key, $attributes, $showLegacyId, $contentType);
        return $response;
    }

    /**
     * Operation getContactAllocationsKeyWithHttpInfo
     *
     * Returns a Contact Allocation
     *
     * @param  string $key The Contact Allocation Key. (required)
     * @param  string|null $attributes Specify the attributes that you want to expose for the Allocation (expose all attributes with &#39;all&#39;). These are in addition to the base attributes (name, path) (optional)
     * @param  bool|null $showLegacyId Display the legacy_id for the Allocation. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getContactAllocationsKey'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array of \SynergiTech\Sage\Model\ContactAllocation, HTTP status code, HTTP response headers (array of strings)
     */
    public function getContactAllocationsKeyWithHttpInfo(
        string $key,
        ?string $attributes = null,
        ?bool $showLegacyId = null,
        string $contentType = self::contentTypes['getContactAllocationsKey'][0]
    ): array
    {
        $request = $this->getContactAllocationsKeyRequest($key, $attributes, $showLegacyId, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    if (in_array('\SynergiTech\Sage\Model\ContactAllocation', ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\SynergiTech\Sage\Model\ContactAllocation' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\SynergiTech\Sage\Model\ContactAllocation', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            $returnType = '\SynergiTech\Sage\Model\ContactAllocation';
            if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\SynergiTech\Sage\Model\ContactAllocation',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getContactAllocationsKeyAsync
     *
     * Returns a Contact Allocation
     *
     * @param  string $key The Contact Allocation Key. (required)
     * @param  string|null $attributes Specify the attributes that you want to expose for the Allocation (expose all attributes with &#39;all&#39;). These are in addition to the base attributes (name, path) (optional)
     * @param  bool|null $showLegacyId Display the legacy_id for the Allocation. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getContactAllocationsKey'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function getContactAllocationsKeyAsync(
        string $key,
        ?string $attributes = null,
        ?bool $showLegacyId = null,
        string $contentType = self::contentTypes['getContactAllocationsKey'][0]
    ): PromiseInterface
    {
        return $this->getContactAllocationsKeyAsyncWithHttpInfo($key, $attributes, $showLegacyId, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getContactAllocationsKeyAsyncWithHttpInfo
     *
     * Returns a Contact Allocation
     *
     * @param  string $key The Contact Allocation Key. (required)
     * @param  string|null $attributes Specify the attributes that you want to expose for the Allocation (expose all attributes with &#39;all&#39;). These are in addition to the base attributes (name, path) (optional)
     * @param  bool|null $showLegacyId Display the legacy_id for the Allocation. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getContactAllocationsKey'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function getContactAllocationsKeyAsyncWithHttpInfo(
        string $key,
        ?string $attributes = null,
        ?bool $showLegacyId = null,
        string $contentType = self::contentTypes['getContactAllocationsKey'][0]
    ): PromiseInterface
    {
        $returnType = '\SynergiTech\Sage\Model\ContactAllocation';
        $request = $this->getContactAllocationsKeyRequest($key, $attributes, $showLegacyId, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getContactAllocationsKey'
     *
     * @param  string $key The Contact Allocation Key. (required)
     * @param  string|null $attributes Specify the attributes that you want to expose for the Allocation (expose all attributes with &#39;all&#39;). These are in addition to the base attributes (name, path) (optional)
     * @param  bool|null $showLegacyId Display the legacy_id for the Allocation. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getContactAllocationsKey'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getContactAllocationsKeyRequest(
        string $key,
        ?string $attributes = null,
        ?bool $showLegacyId = null,
        string $contentType = self::contentTypes['getContactAllocationsKey'][0]
    ): Request
    {

        // verify the required parameter 'key' is set
        if ($key === null || (is_array($key) && count($key) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $key when calling getContactAllocationsKey'
            );
        }




        $resourcePath = '/contact_allocations/{key}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $attributes,
            'attributes', // param base name
            'string', // openApiType
            '', // style
            false, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $showLegacyId,
            'show_legacy_id', // param base name
            'boolean', // openApiType
            '', // style
            false, // explode
            false // required
        ) ?? []);


        // path params
        if ($key !== null) {
            $resourcePath = str_replace(
                '{' . 'key' . '}',
                ObjectSerializer::toPathValue($key),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('subscription-key');
        if ($apiKey !== null) {
            $queryParams['subscription-key'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Ocp-Apim-Subscription-Key');
        if ($apiKey !== null) {
            $headers['Ocp-Apim-Subscription-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation postContactAllocations
     *
     * Creates a Contact Allocation
     *
     * @param  \SynergiTech\Sage\Model\PostContactAllocations|null $postContactAllocations postContactAllocations (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['postContactAllocations'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return \SynergiTech\Sage\Model\ContactAllocation
     */
    public function postContactAllocations(
        ?\SynergiTech\Sage\Model\PostContactAllocations $postContactAllocations = null,
        string $contentType = self::contentTypes['postContactAllocations'][0]
    ): \SynergiTech\Sage\Model\ContactAllocation
    {
        list($response) = $this->postContactAllocationsWithHttpInfo($postContactAllocations, $contentType);
        return $response;
    }

    /**
     * Operation postContactAllocationsWithHttpInfo
     *
     * Creates a Contact Allocation
     *
     * @param  \SynergiTech\Sage\Model\PostContactAllocations|null $postContactAllocations (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['postContactAllocations'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array of \SynergiTech\Sage\Model\ContactAllocation, HTTP status code, HTTP response headers (array of strings)
     */
    public function postContactAllocationsWithHttpInfo(
        ?\SynergiTech\Sage\Model\PostContactAllocations $postContactAllocations = null,
        string $contentType = self::contentTypes['postContactAllocations'][0]
    ): array
    {
        $request = $this->postContactAllocationsRequest($postContactAllocations, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 201:
                    if (in_array('\SynergiTech\Sage\Model\ContactAllocation', ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\SynergiTech\Sage\Model\ContactAllocation' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\SynergiTech\Sage\Model\ContactAllocation', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            $returnType = '\SynergiTech\Sage\Model\ContactAllocation';
            if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 201:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\SynergiTech\Sage\Model\ContactAllocation',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation postContactAllocationsAsync
     *
     * Creates a Contact Allocation
     *
     * @param  \SynergiTech\Sage\Model\PostContactAllocations|null $postContactAllocations (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['postContactAllocations'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function postContactAllocationsAsync(
        ?\SynergiTech\Sage\Model\PostContactAllocations $postContactAllocations = null,
        string $contentType = self::contentTypes['postContactAllocations'][0]
    ): PromiseInterface
    {
        return $this->postContactAllocationsAsyncWithHttpInfo($postContactAllocations, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation postContactAllocationsAsyncWithHttpInfo
     *
     * Creates a Contact Allocation
     *
     * @param  \SynergiTech\Sage\Model\PostContactAllocations|null $postContactAllocations (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['postContactAllocations'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function postContactAllocationsAsyncWithHttpInfo(
        ?\SynergiTech\Sage\Model\PostContactAllocations $postContactAllocations = null,
        string $contentType = self::contentTypes['postContactAllocations'][0]
    ): PromiseInterface
    {
        $returnType = '\SynergiTech\Sage\Model\ContactAllocation';
        $request = $this->postContactAllocationsRequest($postContactAllocations, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'postContactAllocations'
     *
     * @param  \SynergiTech\Sage\Model\PostContactAllocations|null $postContactAllocations (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['postContactAllocations'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function postContactAllocationsRequest(
        ?\SynergiTech\Sage\Model\PostContactAllocations $postContactAllocations = null,
        string $contentType = self::contentTypes['postContactAllocations'][0]
    ): Request
    {



        $resourcePath = '/contact_allocations';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($postContactAllocations)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($postContactAllocations));
            } else {
                $httpBody = $postContactAllocations;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('subscription-key');
        if ($apiKey !== null) {
            $queryParams['subscription-key'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Ocp-Apim-Subscription-Key');
        if ($apiKey !== null) {
            $headers['Ocp-Apim-Subscription-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation putContactAllocationsKey
     *
     * Updates a Contact Allocation
     *
     * @param  string $key The Contact Allocation Key. (required)
     * @param  \SynergiTech\Sage\Model\PutContactAllocations|null $putContactAllocations putContactAllocations (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['putContactAllocationsKey'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return \SynergiTech\Sage\Model\ContactAllocation
     */
    public function putContactAllocationsKey(
        string $key,
        ?\SynergiTech\Sage\Model\PutContactAllocations $putContactAllocations = null,
        string $contentType = self::contentTypes['putContactAllocationsKey'][0]
    ): \SynergiTech\Sage\Model\ContactAllocation
    {
        list($response) = $this->putContactAllocationsKeyWithHttpInfo($key, $putContactAllocations, $contentType);
        return $response;
    }

    /**
     * Operation putContactAllocationsKeyWithHttpInfo
     *
     * Updates a Contact Allocation
     *
     * @param  string $key The Contact Allocation Key. (required)
     * @param  \SynergiTech\Sage\Model\PutContactAllocations|null $putContactAllocations (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['putContactAllocationsKey'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array of \SynergiTech\Sage\Model\ContactAllocation, HTTP status code, HTTP response headers (array of strings)
     */
    public function putContactAllocationsKeyWithHttpInfo(
        string $key,
        ?\SynergiTech\Sage\Model\PutContactAllocations $putContactAllocations = null,
        string $contentType = self::contentTypes['putContactAllocationsKey'][0]
    ): array
    {
        $request = $this->putContactAllocationsKeyRequest($key, $putContactAllocations, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    if (in_array('\SynergiTech\Sage\Model\ContactAllocation', ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\SynergiTech\Sage\Model\ContactAllocation' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\SynergiTech\Sage\Model\ContactAllocation', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            $returnType = '\SynergiTech\Sage\Model\ContactAllocation';
            if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\SynergiTech\Sage\Model\ContactAllocation',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation putContactAllocationsKeyAsync
     *
     * Updates a Contact Allocation
     *
     * @param  string $key The Contact Allocation Key. (required)
     * @param  \SynergiTech\Sage\Model\PutContactAllocations|null $putContactAllocations (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['putContactAllocationsKey'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function putContactAllocationsKeyAsync(
        string $key,
        ?\SynergiTech\Sage\Model\PutContactAllocations $putContactAllocations = null,
        string $contentType = self::contentTypes['putContactAllocationsKey'][0]
    ): PromiseInterface
    {
        return $this->putContactAllocationsKeyAsyncWithHttpInfo($key, $putContactAllocations, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation putContactAllocationsKeyAsyncWithHttpInfo
     *
     * Updates a Contact Allocation
     *
     * @param  string $key The Contact Allocation Key. (required)
     * @param  \SynergiTech\Sage\Model\PutContactAllocations|null $putContactAllocations (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['putContactAllocationsKey'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function putContactAllocationsKeyAsyncWithHttpInfo(
        string $key,
        ?\SynergiTech\Sage\Model\PutContactAllocations $putContactAllocations = null,
        string $contentType = self::contentTypes['putContactAllocationsKey'][0]
    ): PromiseInterface
    {
        $returnType = '\SynergiTech\Sage\Model\ContactAllocation';
        $request = $this->putContactAllocationsKeyRequest($key, $putContactAllocations, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'putContactAllocationsKey'
     *
     * @param  string $key The Contact Allocation Key. (required)
     * @param  \SynergiTech\Sage\Model\PutContactAllocations|null $putContactAllocations (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['putContactAllocationsKey'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function putContactAllocationsKeyRequest(
        string $key,
        ?\SynergiTech\Sage\Model\PutContactAllocations $putContactAllocations = null,
        string $contentType = self::contentTypes['putContactAllocationsKey'][0]
    ): Request
    {

        // verify the required parameter 'key' is set
        if ($key === null || (is_array($key) && count($key) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $key when calling putContactAllocationsKey'
            );
        }



        $resourcePath = '/contact_allocations/{key}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($key !== null) {
            $resourcePath = str_replace(
                '{' . 'key' . '}',
                ObjectSerializer::toPathValue($key),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($putContactAllocations)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($putContactAllocations));
            } else {
                $httpBody = $putContactAllocations;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('subscription-key');
        if ($apiKey !== null) {
            $queryParams['subscription-key'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Ocp-Apim-Subscription-Key');
        if ($apiKey !== null) {
            $headers['Ocp-Apim-Subscription-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PUT',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption(): array
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
