<?php
/**
 * ComponentTaxRateTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Sage One - Accounts - v3 UKI
 *
 * Documentation of the Sage Business Cloud Accounting API.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.43
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ComponentTaxRateTest Class Doc Comment
 *
 * @category    Class
 * @description ComponentTaxRate
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ComponentTaxRateTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ComponentTaxRate"
     */
    public function testComponentTaxRate()
    {
    }

    /**
     * Test attribute "legacy_id"
     */
    public function testPropertyLegacyId()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "displayed_as"
     */
    public function testPropertyDisplayedAs()
    {
    }

    /**
     * Test attribute "path"
     */
    public function testPropertyPath()
    {
    }

    /**
     * Test attribute "created_at"
     */
    public function testPropertyCreatedAt()
    {
    }

    /**
     * Test attribute "updated_at"
     */
    public function testPropertyUpdatedAt()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "agency"
     */
    public function testPropertyAgency()
    {
    }

    /**
     * Test attribute "percentage"
     */
    public function testPropertyPercentage()
    {
    }

    /**
     * Test attribute "percentages"
     */
    public function testPropertyPercentages()
    {
    }

    /**
     * Test attribute "is_visible"
     */
    public function testPropertyIsVisible()
    {
    }

    /**
     * Test attribute "retailer"
     */
    public function testPropertyRetailer()
    {
    }

    /**
     * Test attribute "editable"
     */
    public function testPropertyEditable()
    {
    }

    /**
     * Test attribute "deletable"
     */
    public function testPropertyDeletable()
    {
    }

    /**
     * Test attribute "is_combined_rate"
     */
    public function testPropertyIsCombinedRate()
    {
    }
}
