<?php
/**
 * ContactTaxTreatmentTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Sage One - Accounts - v3 UKI
 *
 * Documentation of the Sage Business Cloud Accounting API.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.43
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ContactTaxTreatmentTest Class Doc Comment
 *
 * @category    Class
 * @description ContactTaxTreatment
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ContactTaxTreatmentTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ContactTaxTreatment"
     */
    public function testContactTaxTreatment()
    {
    }

    /**
     * Test attribute "home_tax"
     */
    public function testPropertyHomeTax()
    {
    }

    /**
     * Test attribute "eu_tax_registered"
     */
    public function testPropertyEuTaxRegistered()
    {
    }

    /**
     * Test attribute "eu_not_tax_registered"
     */
    public function testPropertyEuNotTaxRegistered()
    {
    }

    /**
     * Test attribute "rest_of_world_tax"
     */
    public function testPropertyRestOfWorldTax()
    {
    }

    /**
     * Test attribute "is_importer"
     */
    public function testPropertyIsImporter()
    {
    }
}
